# Generated by Django 2.0.4 on 2018-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cityfood',
            fields=[
                ('food_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('food_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('food_info', models.CharField(blank=True, max_length=2000, null=True)),
                ('food_where', models.CharField(blank=True, max_length=2000, null=True)),
                ('food_city', models.CharField(blank=True, max_length=255, null=True)),
                ('food_web', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cityfood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citygods',
            fields=[
                ('gods_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gods_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('gods_info', models.CharField(blank=True, max_length=2550, null=True)),
                ('gods_where', models.CharField(blank=True, max_length=255, null=True)),
                ('gods_city', models.CharField(blank=True, max_length=255, null=True)),
                ('gods_web', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'citygods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cityrestaurant',
            fields=[
                ('rest_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rest_city', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_info', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_food', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_addre', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_time', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_price', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_score', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_web', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cityrestaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cityshop',
            fields=[
                ('shop_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shop_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_addre', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_info', models.CharField(blank=True, max_length=2000, null=True)),
                ('shop_score', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_time', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_city', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_web', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cityshop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citysight',
            fields=[
                ('sight_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sight_city', models.CharField(blank=True, max_length=255, null=True)),
                ('sight_pic', models.CharField(blank=True, max_length=1000, null=True)),
                ('sight_info', models.CharField(blank=True, max_length=2550, null=True)),
                ('sight_score', models.CharField(blank=True, max_length=255, null=True)),
                ('sight_addre', models.CharField(blank=True, max_length=500, null=True)),
                ('sight_time', models.CharField(blank=True, max_length=255, null=True)),
                ('sight_web', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'citysight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citytravel',
            fields=[
                ('travel_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('travel_days', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_price', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_time', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_places', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_info', models.CharField(blank=True, max_length=20000, null=True)),
                ('travel_city', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_web', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'citytravel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cityurl',
            fields=[
                ('city_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('city_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('city_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cityurl',
                'managed': False,
            },
        ),
    ]
